# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

svinecop_create_cpp <- function(svine_r) {
    .Call(`_svines_svinecop_create_cpp`, svine_r)
}

svinecop_select_cpp <- function(data, p, var_types, out_vertices, in_vertices, is_structure_provided, structure, family_set, par_method, nonpar_method, mult, trunc_lvl, tree_criterion, threshold, selection_criterion, weights, psi0, select_trunc_lvl, select_threshold, preselect_families, show_trace, num_threads) {
    .Call(`_svines_svinecop_select_cpp`, data, p, var_types, out_vertices, in_vertices, is_structure_provided, structure, family_set, par_method, nonpar_method, mult, trunc_lvl, tree_criterion, threshold, selection_criterion, weights, psi0, select_trunc_lvl, select_threshold, preselect_families, show_trace, num_threads)
}

svinecop_loglik_cpp <- function(u, svinecop_r, cores) {
    .Call(`_svines_svinecop_loglik_cpp`, u, svinecop_r, cores)
}

svinecop_sim_cpp <- function(svinecop_r, n, rep, data, qrng, cores, seeds) {
    .Call(`_svines_svinecop_sim_cpp`, svinecop_r, n, rep, data, qrng, cores, seeds)
}

svinecop_pseudo_residuals_cpp <- function(u, svinecop_r, num_threads) {
    .Call(`_svines_svinecop_pseudo_residuals_cpp`, u, svinecop_r, num_threads)
}

svinecop_scores_cpp <- function(u, svinecop_r, num_threads) {
    .Call(`_svines_svinecop_scores_cpp`, u, svinecop_r, num_threads)
}

svinecop_hessian_cpp <- function(u, svinecop_r, num_threads) {
    .Call(`_svines_svinecop_hessian_cpp`, u, svinecop_r, num_threads)
}

with_parameters_cop_cpp <- function(svinecop_r, parameters) {
    .Call(`_svines_with_parameters_cop_cpp`, svinecop_r, parameters)
}

